# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from qtwidgets import PasswordEdit

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1100, 858)
        Login.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Login.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setGeometry(QtCore.QRect(240, 70, 641, 741))
        self.widget.setStyleSheet("border-radius:50px;\n"
"background-color: rgb(77, 77, 77);\n"
"")
        self.widget.setObjectName("widget")
        self.TitleLogin = QtWidgets.QLabel(self.widget)
        self.TitleLogin.setGeometry(QtCore.QRect(260, 110, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLogin.setFont(font)
        self.TitleLogin.setStyleSheet("color:rgb(255,255,255)")
        self.TitleLogin.setObjectName("label")
        self.Email = QtWidgets.QLineEdit(self.widget)
        self.Email.setGeometry(QtCore.QRect(120, 250, 400, 50))
        self.Email.setAutoFillBackground(False)
        self.Email.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(211, 211, 211);\n"
"padding-left:7px;\n"
"color: rgb(40, 40, 40);\n"
"\n"
"")
        self.Email.setText("")
        self.Email.setObjectName("Email")
        
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(120, 360, 400, 50))
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(211, 211, 211);\n"
"padding-left: 7px;\n"
"color: rgb(40, 40, 40)\n"
"\n"
"")
        self.password.setText("")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.AppNametext = QtWidgets.QLabel(self.widget)
        self.AppNametext.setGeometry(QtCore.QRect(170, 0, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AppNametext.setFont(font)
        self.AppNametext.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: none;")
        self.AppNametext.setObjectName("AppNametext")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(120, 500, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.943, x2:1, y2:0, stop:0 rgba(84, 176, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.766, y1:0.153409, x2:1, y2:0, stop:0 rgba(84, 241, 236, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:press{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(117, 255, 251)\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(150, 450, 101, 20))
        self.checkBox.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.wellcomebacktext = QtWidgets.QLabel(self.widget)
        self.wellcomebacktext.setGeometry(QtCore.QRect(240, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wellcomebacktext.setFont(font)
        self.wellcomebacktext.setStyleSheet("color: rgb(255, 255, 255);")
        self.wellcomebacktext.setObjectName("wellcomebacktext")
        self.Hidepassword = QtWidgets.QPushButton(self.widget)
        self.Hidepassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Hidepassword.setStyleSheet("background-color: none;")
        self.Hidepassword.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconLogin/hide_icon_183908.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hidepassword.setIcon(icon)
        self.Hidepassword.setObjectName("Hidepassword")
        self.Showpassword = QtWidgets.QPushButton(self.widget)
        self.Showpassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Showpassword.setStyleSheet("background-color: none;")
        self.Showpassword.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconLogin/show_icon_183921.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Showpassword.setIcon(icon1)
        self.Showpassword.setObjectName("Showpassword")
        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.Hidepassword.hide()
        self.TitleLogin.setText(_translate("Login", "LOGIN"))
        self.Email.setPlaceholderText(_translate("Login", "Enter Email"))
        self.password.setPlaceholderText(_translate("Login", "Enter password"))
        self.AppNametext.setText(_translate("Login", "MOT CONTROL PANEL"))
        self.pushButton.setText(_translate("Login", "LOGIN"))
        self.checkBox.setText(_translate("Login", "Keep Login"))
        self.wellcomebacktext.setText(_translate("Login", "Wellcome back!"))
