# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from qtwidgets import PasswordEdit

class Ui_App(object):
    def setupUi(self,App):
        App.setObjectName("App")
        App.resize(1920, 1080)
        #Login client
        App.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        App.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(App)
        self.widget.setGeometry(QtCore.QRect(610, 70, 641, 741))
        self.widget.setStyleSheet("border-radius:50px;\n"
"background-color: rgb(77, 77, 77);\n"
"")
        self.widget.setObjectName("widget")
        self.TitleLogin = QtWidgets.QLabel(self.widget)
        self.TitleLogin.setGeometry(QtCore.QRect(260, 110, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLogin.setFont(font)
        self.TitleLogin.setStyleSheet("color:rgb(255,255,255)")
        self.TitleLogin.setObjectName("label")
        self.Email = QtWidgets.QLineEdit(self.widget)
        self.Email.setGeometry(QtCore.QRect(120, 250, 400, 50))
        self.Email.setAutoFillBackground(False)
        self.Email.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(211, 211, 211);\n"
"padding-left:7px;\n"
"color: rgb(40, 40, 40);\n"
"\n"
"")
        self.Email.setText("")
        self.Email.setObjectName("Email")
        
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(120, 360, 400, 50))
        self.password.setAutoFillBackground(False)
        self.password.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(211, 211, 211);\n"
"padding-left: 7px;\n"
"color: rgb(40, 40, 40)\n"
"\n"
"")
        self.password.setText("")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.AppNametext = QtWidgets.QLabel(self.widget)
        self.AppNametext.setGeometry(QtCore.QRect(170, 0, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AppNametext.setFont(font)
        self.AppNametext.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: none;")
        self.AppNametext.setObjectName("AppNametext")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(120, 500, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton#pushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.943, x2:1, y2:0, stop:0 rgba(84, 176, 241, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.766, y1:0.153409, x2:1, y2:0, stop:0 rgba(84, 241, 236, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton#pushButton:press{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgb(117, 255, 251)\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(150, 450, 101, 20))
        self.checkBox.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.wellcomebacktext = QtWidgets.QLabel(self.widget)
        self.wellcomebacktext.setGeometry(QtCore.QRect(240, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wellcomebacktext.setFont(font)
        self.wellcomebacktext.setStyleSheet("color: rgb(255, 255, 255);")
        self.wellcomebacktext.setObjectName("wellcomebacktext")
        self.Hidepassword = QtWidgets.QPushButton(self.widget)
        self.Hidepassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Hidepassword.setStyleSheet("background-color: none;")
        self.Hidepassword.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconLogin/hide_icon_183908.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hidepassword.setIcon(icon)
        self.Hidepassword.setObjectName("Hidepassword")
        self.Showpassword = QtWidgets.QPushButton(self.widget)
        self.Showpassword.setGeometry(QtCore.QRect(471, 370, 41, 28))
        self.Showpassword.setStyleSheet("background-color: none;")
        self.Showpassword.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconLogin/show_icon_183921.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Showpassword.setIcon(icon1)
        self.Showpassword.setObjectName("Showpassword")
    
        #dashboard client
        self.dashboard = QtWidgets.QWidget(App)
        self.dashboard.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.dashboard.setStyleSheet("background-color: none;")
        self.dashboard.setObjectName("dashboard")
        self.widget1 = QtWidgets.QWidget(self.dashboard)
        self.widget1.setGeometry(QtCore.QRect(0, 20, 501, 1080))
        self.widget1.setStyleSheet("background-color: #D9D9D9;")
        self.widget1.setObjectName("widget")
        self.helloText = QtWidgets.QLabel(self.widget1)
        self.helloText.setGeometry(QtCore.QRect(38, 45, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.helloText.setFont(font)
        self.helloText.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.helloText.setAlignment(QtCore.Qt.AlignCenter)
        self.helloText.setObjectName("helloText")
        self.nameInfor = QtWidgets.QLabel(self.widget1)
        self.nameInfor.setGeometry(QtCore.QRect(38, 170, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nameInfor.setFont(font)
        self.nameInfor.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.nameInfor.setAlignment(QtCore.Qt.AlignCenter)
        self.nameInfor.setObjectName("nameInfor")
        self.dateofbirthInfor = QtWidgets.QLabel(self.widget1)
        self.dateofbirthInfor.setGeometry(QtCore.QRect(38, 295, 422, 73))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateofbirthInfor.setFont(font)
        self.dateofbirthInfor.setStyleSheet("background-color: #AAAAAA;\n"
"border-radius:25px;")
        self.dateofbirthInfor.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirthInfor.setObjectName("dateofbirthInfor")
        self.logoutButton = QtWidgets.QPushButton(self.widget1)
        self.logoutButton.setGeometry(QtCore.QRect(38, 860, 422, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("background-color: #78A9CA;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-logout-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setObjectName("logoutButton")
        self.fieldListbtn = QtWidgets.QWidget(self.dashboard)
        self.fieldListbtn.setGeometry(QtCore.QRect(500, 20, 1421, 1080))
        self.fieldListbtn.setStyleSheet("background-color: #656464;")
        self.fieldListbtn.setObjectName("fieldListbtn")
        self.btnlListcam_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlListcam_icon.setGeometry(QtCore.QRect(90, 50, 321, 161))
        self.btnlListcam_icon.setStyleSheet("background-color:none;")
        self.btnlListcam_icon.setObjectName("btnlListcam_icon")
        self.listcamPage = QtWidgets.QPushButton(self.btnlListcam_icon)
        self.listcamPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.listcamPage.setFont(font)
        self.listcamPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.listcamPage.setObjectName("listcamPage")
        self.iconListcambtn = QtWidgets.QPushButton(self.btnlListcam_icon)
        self.iconListcambtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconListcambtn.setStyleSheet("background-color:#35B4F9;\n"
"border-radius:25px")
        self.iconListcambtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-list-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconListcambtn.setIcon(icon1)
        self.iconListcambtn.setIconSize(QtCore.QSize(24, 24))
        self.iconListcambtn.setObjectName("iconListcambtn")
        self.btnlListvideovolation_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlListvideovolation_icon.setGeometry(QtCore.QRect(550, 50, 321, 161))
        self.btnlListvideovolation_icon.setStyleSheet("background-color:none;")
        self.btnlListvideovolation_icon.setObjectName("btnlListvideovolation_icon")
        self.videoviolationPage = QtWidgets.QPushButton(self.btnlListvideovolation_icon)
        self.videoviolationPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.videoviolationPage.setFont(font)
        self.videoviolationPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.videoviolationPage.setObjectName("videoviolationPage")
        self.iconListvideoviolationbtn = QtWidgets.QPushButton(self.btnlListvideovolation_icon)
        self.iconListvideoviolationbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconListvideoviolationbtn.setStyleSheet("background-color:rgb(255, 0, 0);\n"
"border-radius:25px")
        self.iconListvideoviolationbtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-cinema-44.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconListvideoviolationbtn.setIcon(icon2)
        self.iconListvideoviolationbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconListvideoviolationbtn.setObjectName("iconListvideoviolationbtn")
        self.btnlChart_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnlChart_icon.setGeometry(QtCore.QRect(1010, 50, 321, 161))
        self.btnlChart_icon.setStyleSheet("background-color:none;")
        self.btnlChart_icon.setObjectName("btnlChart_icon")
        self.ChartPage = QtWidgets.QPushButton(self.btnlChart_icon)
        self.ChartPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ChartPage.setFont(font)
        self.ChartPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.ChartPage.setObjectName("ChartPage")
        self.iconChartbtn = QtWidgets.QPushButton(self.btnlChart_icon)
        self.iconChartbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconChartbtn.setStyleSheet("background-color:#00CD21;\n"
"border-radius:25px")
        self.iconChartbtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-histogram-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconChartbtn.setIcon(icon3)
        self.iconChartbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconChartbtn.setObjectName("iconChartbtn")
        self.btnCreateaccout_icon = QtWidgets.QWidget(self.fieldListbtn)
        self.btnCreateaccout_icon.setGeometry(QtCore.QRect(90, 260, 321, 161))
        self.btnCreateaccout_icon.setStyleSheet("background-color:none;")
        self.btnCreateaccout_icon.setObjectName("btnCreateaccout_icon")
        self.createaccountPage = QtWidgets.QPushButton(self.btnCreateaccout_icon)
        self.createaccountPage.setGeometry(QtCore.QRect(0, 50, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.createaccountPage.setFont(font)
        self.createaccountPage.setStyleSheet("background-color:#B4B4B4;\n"
"border-radius:25px;\n"
"color:rgb(255, 255, 255)")
        self.createaccountPage.setObjectName("createaccountPage")
        self.iconCreateaccountbtn = QtWidgets.QPushButton(self.btnCreateaccout_icon)
        self.iconCreateaccountbtn.setGeometry(QtCore.QRect(30, 0, 80, 80))
        self.iconCreateaccountbtn.setStyleSheet("background-color:rgb(44, 83, 255);\n"
"border-radius:25px;\n"
"")
        self.iconCreateaccountbtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/iconDashboard/icons8-add-user-male-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iconCreateaccountbtn.setIcon(icon4)
        self.iconCreateaccountbtn.setIconSize(QtCore.QSize(28, 28))
        self.iconCreateaccountbtn.setObjectName("iconCreateaccountbtn")
        self.frame = QtWidgets.QFrame(self.dashboard)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 1921, 26))
        self.frame.setStyleSheet("background-color: rgb(90,90,90);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setGeometry(QtCore.QRect(1830, 0, 81, 26))
        self.widget_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:12px;")
        self.widget_7.setObjectName("widget_7")
        self.MinimunBtn = QtWidgets.QPushButton(self.widget_7)
        self.MinimunBtn.setGeometry(QtCore.QRect(10, 1, 24, 24))
        self.MinimunBtn.setStyleSheet("background-color: rgb(140,140,140);\n"
"border-radius:12px")
        self.MinimunBtn.setText("")
        iconMin = QtGui.QIcon()
        iconMin.addPixmap(QtGui.QPixmap("static/icon/minimum-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinimunBtn.setIcon(iconMin)
        self.MinimunBtn.setObjectName("MinimunBtn")
        self.CloseBtn = QtWidgets.QPushButton(self.widget_7)
        self.CloseBtn.setGeometry(QtCore.QRect(50, 1, 24, 24))
        self.CloseBtn.setStyleSheet("background-color: rgb(239, 0, 0);\n"
"border-radius:12px")
        self.CloseBtn.setText("")
        iconClose = QtGui.QIcon()
        iconClose.addPixmap(QtGui.QPixmap("static/icon/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseBtn.setIcon(iconClose)
        self.CloseBtn.setObjectName("CloseBtn")

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)    
    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        self.dashboard.hide()
        App.setWindowTitle(_translate("App", "App"))
        self.Hidepassword.hide()
        self.TitleLogin.setText(_translate("App", "LOGIN"))
        self.Email.setPlaceholderText(_translate("App", "Enter Email"))
        self.password.setPlaceholderText(_translate("App", "Enter password"))
        self.AppNametext.setText(_translate("App", "MOT CONTROL PANEL"))
        self.pushButton.setText(_translate("App", "LOGIN"))
        self.checkBox.setText(_translate("App", "Keep Login"))
        self.wellcomebacktext.setText(_translate("App", "Wellcome back!"))
        self.helloText.setText(_translate("App", "Xin Chào Bạn !"))
        self.nameInfor.setText(_translate("App", "Nguyễn Xuân Phúc"))
        self.dateofbirthInfor.setText(_translate("App", "01/01/2022"))
        self.logoutButton.setText(_translate("App", "Đăng Xuất"))
        self.listcamPage.setText(_translate("App", "Danh sách Camera"))
        self.videoviolationPage.setText(_translate("App", "Video vi phạm"))
        self.ChartPage.setText(_translate("App", "Thống kê"))
        self.createaccountPage.setText(_translate("App", "Tạo tại khoản"))
